defmodule Trygg.Storage.Local do
  @moduledoc """
  Filesystem-backed `Trygg.Storage`. Objects are plain files under a base
  directory (`config :trygg, Trygg.Storage, base_dir: …`, defaulting to
  `priv/uploads`). Used on dev and test; production uses `Trygg.Storage.S3`.

  Keys are always generated by `Trygg.Log` (a numeric child id plus a UUID),
  never taken raw from a request, and `path/1` still normalises the key and
  confirms the result stays inside the base directory.
  """

  @behaviour Trygg.Storage

  # `path/1` normalises the key and verifies containment in the base dir.
  # sobelow_skip ["Traversal.FileModule"]
  @impl true
  def put(key, body, _content_type) do
    with {:ok, path} <- path(key),
         :ok <- File.mkdir_p(Path.dirname(path)) do
      File.write(path, body)
    end
  end

  # sobelow_skip ["Traversal.FileModule"]
  @impl true
  def get(key) do
    with {:ok, path} <- path(key) do
      File.read(path)
    end
  end

  # sobelow_skip ["Traversal.FileModule"]
  @impl true
  def delete(key) do
    with {:ok, path} <- path(key) do
      case File.rm(path) do
        :ok -> :ok
        {:error, :enoent} -> :ok
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @doc false
  def base_dir do
    :trygg
    |> Application.get_env(Trygg.Storage, [])
    |> Keyword.get(:base_dir)
    |> case do
      nil -> Path.join(:code.priv_dir(:trygg), "uploads")
      dir -> dir
    end
  end

  # Resolve a key to an absolute path: drop "", "." and ".." segments, then
  # expand and confirm the result is still under the base directory. Returns
  # `{:error, :invalid_key}` for anything that would escape.
  defp path(key) do
    base = base_dir() |> Path.expand()

    resolved =
      key
      |> Path.split()
      |> Enum.reject(&(&1 in ["", ".", ".."]))
      |> Path.join()
      |> then(&Path.expand(&1, base))

    if resolved == base or String.starts_with?(resolved, base <> "/") do
      {:ok, resolved}
    else
      {:error, :invalid_key}
    end
  end
end
