defmodule TryggWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :trygg

  # Cookie session: signed and encrypted. `secure` is compile-time so the
  # production release always sets the Secure flag; Fly terminates TLS.
  @session_options [
    store: :cookie,
    key: "_trygg_key",
    signing_salt: "P//bBZWg",
    encryption_salt: "trygg_cookie",
    same_site: "Lax",
    secure: Mix.env() == :prod
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :x_headers, :uri, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :x_headers, :uri, session: @session_options]]

  # Fly (and any other orchestrator) probes this before Plug.Static / session.
  plug TryggWeb.Health

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :trygg,
    gzip: not code_reloading?,
    # In dev, force the browser to revalidate assets so a normal (Cmd+R)
    # reload can't repaint with a stale app.css/app.js from the HTTP cache.
    cache_control_for_etags: if(code_reloading?, do: "no-cache", else: "public"),
    only: TryggWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :trygg
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TryggWeb.Router
end
