import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :trygg, TryggWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Compile-time: Plug.SSL is injected at the front of the endpoint pipeline.
  # Fly terminates TLS at the edge; rewrite_on trusts X-Forwarded-* so HSTS
  # and https redirects work. IP / loopback hosts are Fly machine health checks
  # (they never pass through the edge proxy).
  force_ssl: [
    hsts: true,
    host: nil,
    rewrite_on: [:x_forwarded_proto, :x_forwarded_host, :x_forwarded_port],
    exclude: [
      hosts: ["localhost", "127.0.0.1"],
      paths: ["/health"],
      conn: {TryggWeb.Health, :ssl_excluded?, []}
    ]
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :logger, :default_formatter,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id, :crash_reason]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
