#!/usr/bin/env python3
"""Render the 💧 / 💩 / 💧💩 icons to RGB565 arrays in src/icons.h.

macOS only (uses Apple Color Emoji, which Pillow can render at size 160).
The icons are pre-composited onto BG, so they must match the firmware's
background colour. Re-run only to change the icons: `make fw-icons`.
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONT = "/System/Library/Fonts/Apple Color Emoji.ttc"
SIZE = 64
BG = (16, 20, 24)  # keep in sync with COLOR_BG in src/main.cpp


def emoji(char: str) -> Image.Image:
    img = Image.new("RGBA", (160, 160), (0, 0, 0, 0))
    ImageDraw.Draw(img).text((0, 0), char, font=ImageFont.truetype(FONT, 160), embedded_color=True)
    return img.crop(img.getbbox())


def fit(img: Image.Image, box: int) -> Image.Image:
    scale = box / max(img.size)
    return img.resize((max(1, round(img.width * scale)), max(1, round(img.height * scale))), Image.LANCZOS)


def canvas() -> Image.Image:
    return Image.new("RGBA", (SIZE, SIZE), BG + (255,))


def centred(base: Image.Image, img: Image.Image, cx: int, cy: int) -> None:
    base.alpha_composite(img, (cx - img.width // 2, cy - img.height // 2))


def single(char: str) -> Image.Image:
    base = canvas()
    centred(base, fit(emoji(char), SIZE), SIZE // 2, SIZE // 2)
    return base


def mixed() -> Image.Image:
    base = canvas()
    centred(base, fit(emoji("💧"), 40), 18, 24)
    centred(base, fit(emoji("💩"), 44), 40, 40)
    return base


def rgb565(img: Image.Image) -> list[int]:
    return [((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3) for r, g, b, _ in img.convert("RGBA").getdata()]


def array(name: str, img: Image.Image) -> str:
    px = rgb565(img)
    rows = ["  " + ", ".join(f"0x{v:04X}" for v in px[i : i + 12]) + "," for i in range(0, len(px), 12)]
    return f"static const uint16_t {name}[{SIZE * SIZE}] PROGMEM = {{\n" + "\n".join(rows) + "\n};\n"


out = Path(__file__).resolve().parent.parent / "src" / "icons.h"
out.write_text(
    "// Generated by tools/gen_icons.py — do not edit.\n#pragma once\n#include <Arduino.h>\n\n"
    f"static const int ICON_SIZE = {SIZE};\n\n"
    + array("ICON_PEE", single("💧")) + "\n"
    + array("ICON_POO", single("💩")) + "\n"
    + array("ICON_MIXED", mixed())
)
print("wrote", out)
