#!/usr/bin/env python3
"""Render the 💧 / 💩 / 💧💩 icons to RGB565 arrays in src/icons.h.

macOS only (uses Apple Color Emoji, which Pillow can render at size 160).
The icons are pre-composited onto BG (tiles) and OK_BG (full-screen "logged"
view), so they must match the firmware's colours. Re-run only to change the icons: `make fw-icons`.
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONT = "/System/Library/Fonts/Apple Color Emoji.ttc"
SIZE = 64
BG = (16, 20, 24)  # keep in sync with COLOR_BG in src/main.cpp
OK_BG = (34, 160, 80)  # keep in sync with COLOR_OK_BG in src/main.cpp
BIG_SIZE = 96


def emoji(char: str) -> Image.Image:
    img = Image.new("RGBA", (160, 160), (0, 0, 0, 0))
    ImageDraw.Draw(img).text((0, 0), char, font=ImageFont.truetype(FONT, 160), embedded_color=True)
    return img.crop(img.getbbox())


def fit(img: Image.Image, box: int) -> Image.Image:
    scale = box / max(img.size)
    return img.resize((max(1, round(img.width * scale)), max(1, round(img.height * scale))), Image.LANCZOS)


def canvas(size: int, bg: tuple) -> Image.Image:
    return Image.new("RGBA", (size, size), bg + (255,))


def centred(base: Image.Image, img: Image.Image, cx: int, cy: int) -> None:
    base.alpha_composite(img, (cx - img.width // 2, cy - img.height // 2))


def single(char: str, size: int, bg: tuple) -> Image.Image:
    base = canvas(size, bg)
    centred(base, fit(emoji(char), size), size // 2, size // 2)
    return base


def mixed(size: int, bg: tuple) -> Image.Image:
    base = canvas(size, bg)
    u = size / 64  # laid out on a 64px grid
    centred(base, fit(emoji("💧"), round(40 * u)), round(18 * u), round(24 * u))
    centred(base, fit(emoji("💩"), round(44 * u)), round(40 * u), round(40 * u))
    return base


def rgb565(img: Image.Image) -> list[int]:
    return [((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3) for r, g, b, _ in img.convert("RGBA").getdata()]


def array(name: str, img: Image.Image) -> str:
    px = rgb565(img)
    rows = ["  " + ", ".join(f"0x{v:04X}" for v in px[i : i + 12]) + "," for i in range(0, len(px), 12)]
    return f"static const uint16_t {name}[{img.width * img.height}] PROGMEM = {{\n" + "\n".join(rows) + "\n};\n"


kinds = (("PEE", lambda s, bg: single("💧", s, bg)), ("POO", lambda s, bg: single("💩", s, bg)), ("MIXED", mixed))
parts = [
    "// Generated by tools/gen_icons.py — do not edit.\n#pragma once\n#include <Arduino.h>\n\n",
    f"static const int ICON_SIZE = {SIZE};\nstatic const int ICON_BIG_SIZE = {BIG_SIZE};\n\n",
]
for name, draw in kinds:  # small, on the idle background (the three tiles)
    parts.append(array(f"ICON_{name}", draw(SIZE, BG)) + "\n")
for name, draw in kinds:  # big, on the "logged" full-screen background
    parts.append(array(f"ICON_{name}_BIG", draw(BIG_SIZE, OK_BG)) + "\n")

out = Path(__file__).resolve().parent.parent / "src" / "icons.h"
out.write_text("".join(parts))
print("wrote", out)
